Dipesh_Pal/Dipesh_Pal/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from home.sitemaps import PostSitemap, StaticViewSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'posts': PostSitemap,
    'static': StaticViewSitemap(['sitemap',
                                 'home:list',
                                 'home:News', 'home:android', 'home:PC', 'home:Others', 'home:create',
                                 'about:about',
                                 'disclaimer:disclaimer',
                                 'contact_us:contact_us',
                                 'videos:videos_page',
                                 ]),
}


urlpatterns = [
    url('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('accounts.urls'), name='accounts'),
    url(r'^', include('home.urls'), name='home'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^about/', include('about.urls'), name='about'),
    url(r'^disclaimer/', include('disclaimer.urls'), name='disclaimer'),
    url(r'^privacy_policy/', include('privacy_policy.urls')),
    url(r'^contact_us/', include('contact_us.urls'), name='contact_us'),
    url(r'^videos/', include('videos.urls'), name='videos'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dipesh_Pal/home/urls.py
from django.conf.urls import url

from . import views


app_name = 'home'


urlpatterns = [
    url(r'^$', views.homepage, name="list"),
    url(r'^News/', views.News, name="News"),
    url(r'^Android/', views.android, name="android"),
    url(r'^PC/', views.PC, name="PC"),
    url(r'^Offers/', views.Offers, name="Offers"),
    url(r'^Others/', views.Others, name="Others"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/', views.article_update, name="post_edit"),
    url(r'^(?P<slug>[\w-]+)/delete/', views.article_delete, name="delete_post"),
]

Dipesh_Pal/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Google ads -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-6717309277759744",
        enable_page_level_ads: true
      });
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="Dipesh Pal" content="">

    {% block title %}<title>Dipesh Pal</title>{% endblock %}

    <!-- Custom styles for this template -->
    <link href="{% static '/css/business-frontpage.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Youmax Scripts -->
    <link href="{% static '/css/youmax.min.css' %}" rel="stylesheet" type="text/css">

     <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png"  href="http://gdurl.com/jScY" %}>

    <!-- Sub Menu -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

</head>

<body class="hm-gradient">
    <header class="site-header">
    <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'home:list' %}"><img src="/media/logo/logo.png" style="height:70px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                  <!---HOME--->
                    <li {% block homeli %} {% endblock %}>
                      <a class="nav-link" href="{% url 'home:list' %}">Home
                          <span class="sr-only">(current)</span>
                      </a>
                    </li>

                    <li {% block videosli %} {% endblock %}>
                      <a class="nav-link" href="/videos/videos.html">Videos</a>
                    </li>

                  <!---Login / Signup / Logout--->
                  {% if user.is_authenticated%}
                        {% if user.is_staff %}
                          <li {% block articleCreateli %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/create/">Create New Article</a>
                          </li>
                        {% endif %}


                        <li {% block profileli %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/accounts/profile/">Profile</a>
                        </li>

                        <li class="nav-item" >
                            <form id="logout_btn" action="/accounts/logout/" method="post">
                            {% csrf_token %}
                                <input type="hidden" name="logout" value="Logout" />
                                <a class="nav-link" onmouseover="this.style.cursor='hand'"
                                        onclick="document.getElementById('logout_btn').submit();">Logout
                                </a>
                            </form>
                        </li>
                  {% else %}
                    <li  {% block loginli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/login/">Login</a>
                    </li>
                    <li {% block signupli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/signup/">Sign Up</a>
                    </li>
                  {% endif %}
                  <!---End Login / Signup / Logout--->
                  <li {% block aboutli %} {% endblock %} class="nav-item">
                         <a class="nav-link" href="/about/about.html">About</a>
                  </li>
              </ul>
            </div>
          </div>
        </nav>
    </header>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<br><br>
<!-- SUB Menu -->
    <main>
        <!--MDB Navbars-->
        <div class="container-fluid mt-4">
            <!--Navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
                <a class="navbar-brand font-bold" href="{% url 'home:list' %}">Topics-</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText1" aria-controls="navbarText1" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText1">
                    <ul class="navbar-nav mr-auto">
                        <li  {% block Allli %} {% endblock %} class="nav-item">
                            <a class="nav-link waves-effect waves-light"  href="{% url 'home:list' %}">All <span class="sr-only">(current)</span></a>
                        </li>
                        <li {% block Newsli %} {% endblock %} class="nav-item">
                            <a class="nav-link waves-effect waves-light" href="{% url 'home:News' %}">News <span class="sr-only">(current)</span></a>
                        </li>
                        <li  {% block Androidli %} {% endblock %} class="nav-item">
                            <a class="nav-link waves-effect waves-light" href="{% url 'home:android' %}">Android</a>
                        </li>
                        <li  {% block Pcli %} {% endblock %} class="nav-item">
                            <a class="nav-link waves-effect waves-light" href="{% url 'home:PC' %}">PC</a>
                        </li>
                        <li  {% block Offersli %} {% endblock %} class="nav-item">
                            <a class="nav-link waves-effect waves-light" href="{% url 'home:Offers' %}">Offers</a>
                        </li>
                        <li  {% block Othersli %} {% endblock %} class="nav-item">
                            <a class="nav-link waves-effect waves-light" href="{% url 'home:Others' %}">Others</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <!--/.Navbar -->
        </div>
    </main>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.1/js/mdb.min.js"></script>
<!-- End SUB Menu -->

    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>

        <div class="col-md-4">
          <div class="content-section">
            <h5 class="font-weight-normal">Follow us on-</h5>
              <ul class="list-group">
                <a class="text-muted" href="https://www.youtube.com/DIPESHPAL17">Subscribe on YouTube-</a>
                    <a class="text-muted" href="https://www.youtube.com/DIPESHPAL17"><img src="/media/social/YouTube.png" style="height:50px; width: 50px"> <b> {{ youtube_subscriber }} Subscriber</b></a>

                <a class="text-muted" href="https://www.instagram.com/dipesh_pal17">Follow on Instagram-</a>
                    <a class="text-muted" href="https://www.instagram.com/dipesh_pal17"> <img src="/media/social/Instagram.png" style="height:50px; width: 50px"> <b> {{ instagram_followers }} Followers</b></a>

                <a class="text-muted" href="https://twitter.com/Dipesh17pal">Follow on Twitter-</a>
                    <a class="text-muted" href="https://twitter.com/Dipesh17pal"><img src="/media/social/Twitter.png" style="height:50px; width: 50px"> <b> {{ twitter_followers }} Followers</b></a>

                <a class="text-muted" href="https://facebook.com/dipeshpal17">Follow on Facebook-</a>
                    <a class="text-muted" href="https://facebook.com/dipeshpal17"><img src="/media/social/Facebook.png" style="height:50px; width: 50px"> <b> 500+ Followers</b></a>
              </ul>
          </div>
               <div class="content-section">
                  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Django-DipeshPal Right Side -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-6717309277759744"
                         data-ad-slot="1510496486"
                         data-ad-format="auto"
                         data-full-width-responsive="true"></ins>
                    <script>
                     (adsbygoogle = window.adsbygoogle || []).push({});
                  </script>
              </div>
        </div>
      </div>
    </main>


    <!-- Footer -->
    <footer class="py-5 bg-dark">
       <div align="center">
           <h2 id="text_about_heading" style="color: #ffffff; text-size: 5%">We are on Social</h2>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/YouTube.png"></a>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Instagram.png"></a>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Facebook.png"></a>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Twitter.png"></a>
       </div>

      <div class="container">
          <!-- Bottom -->
          <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
                <a href="/about/about.html" class="text-light">About</a>
            </li>

            <li class="list-inline-item">
                <a href="/disclaimer/disclaimer.html" class="text-light">Disclaimer</a>
            </li>

            <li class="list-inline-item">
                <a href="/contact_us/contact_us.html" class="text-light">Contact Us</a>
            </li>

            <li class="list-inline-item">
                <a href="/privacy_policy/privacy_policy.html" class="text-light">Privacy Policy</a>
            </li>
          </ul>
      </div>
      <p class="m-0 text-center text-white">Copyright &copy; Dipesh Pal 2019-2020. All Rights Reserved</p>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Js min -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.min.js"></script>

    <script>
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text()
                console.log(content)
                var markedContent = marked(content)
                console.log(markedContent)
                $(this).html(markedContent)
             })
        })
    </script>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="/static/js/youmax.min.js" type="text/javascript"></script>

</body>
</html>

Dipesh_Pal/templates/base_layout2.html
    {% load static from staticfiles %}


    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="Dipesh Pal" content="">

        <!-- favicon -->
        <link rel="shortcut icon" type="image/png"  href="http://gdurl.com/jScY" %}>

        {% block title %}<title>Dipesh Pal</title>{% endblock %}

        <!-- Custom styles for this template -->
        <link href="{% static '/css/business-frontpage.css' %}" rel="stylesheet">
        <link href="{% static '/css/all_custom.css' %}" rel="stylesheet">

        <!-- Bootstrap core CSS -->
        <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!--<script src="./jquery.min.js"></script>-->
        <script src="{% static '/jquery/jquery-1.9.1.min.js' %}"></script>
        <script src="{% static '/js/all_custom.js' %}"></script>
        <script src="{% static '/js/youmax.js' %}"></script>
        <link href="{% static '/css/youmax.css' %}" rel="stylesheet" />

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png"  href="http://gdurl.com/jScY" %}>

    {% block script %} {% endblock %}
</head>

<body>
    <div class="bodydiv">
    <header>
    <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'home:list' %}"><img src="/media/logo/logo.png" style="height:50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                  <!---HOME--->
                  <li {% block homeli %} {% endblock %}>
                      <a class="nav-link" href="{% url 'home:list' %}">Home
                          <span class="sr-only">(current)</span>
                      </a>
                  </li>

                  <li {% block videosli %} {% endblock %}>
                      <a class="nav-link" href="/videos/videos.html">Videos
                          <!--<span class="sr-only">(current)</span>-->
                      </a>
                  </li>

                  <!---Login / Signup / Logout--->
                  {% if user.is_authenticated%}
                        {% if user.is_staff %}
                          <li {% block articleCreateli %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/create/">Create New Article</a>
                          </li>
                        {% endif %}


                        <li {% block profileli %} {% endblock %} class="nav-item">
                              <a class="nav-link" href="/accounts/profile/">Profile</a>
                        </li>

                        <li class="nav-item" >
                            <form id="logout_btn" action="/accounts/logout/" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="logout" value="Logout" />
                                <a class="nav-link" onmouseover="this.style.cursor='hand'"
                                   onclick="document.getElementById('logout_btn').submit();">Logout
                                </a>
                            </form>
                        </li>
                  {% else %}
                    <li {% block loginli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/login/">Login</a>
                    </li>
                    <li {% block signupli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/signup/">Sign Up</a>
                    </li>
                  {% endif %}
                  <!---End Login / Signup / Logout--->
                  <li {% block aboutli %} {% endblock %} class="nav-item">
                         <a class="nav-link" href="/about/about.html">About</a>
                  </li>

              </ul>
            </div>
          </div>
        </nav>
    </header>
        <!--<div class="block_content_baseLayout2">-->

            <!--&lt;!&ndash; Google ads for content Start &ndash;&gt;-->
             <!--<div class="content-section">-->
                  <!--<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>-->
                    <!--<ins class="adsbygoogle"-->
                         <!--style="display:block; text-align:center;"-->
                         <!--data-ad-layout="in-article"-->
                         <!--data-ad-format="fluid"-->
                         <!--data-ad-client="ca-pub-6717309277759744"-->
                         <!--data-ad-slot="5066598116"></ins>-->
                  <!--<script>-->
                     <!--(adsbygoogle = window.adsbygoogle || []).push({});-->
                  <!--</script>-->
             <!--</div>-->
            <!--&lt;!&ndash; Google ads for content End &ndash;&gt;-->

            {% block content %}
            {% endblock %}

            {% block head_extra %}
            {% endblock head_extra %}
        </div>
    </div>
    <br><br><br><br><br><br>

    <!-- Footer -->
   <footer class="py-5 bg-dark">
       <div align="center">
           <h2 id="text_about_heading" style="color: #ffffff; text-size: 5%">We are on Social</h2>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/YouTube.png"></a>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Instagram.png"></a>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Facebook.png"></a>
           <a href="https://www.youtube.com/DipeshPal17" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Twitter.png"></a>
       </div>

      <div class="container">
          <!-- Bottom -->
          <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
                <a href="/about/about.html" class="text-light">About</a>
            </li>

            <li class="list-inline-item">
                <a href="/disclaimer/disclaimer.html" class="text-light">Disclaimer</a>
            </li>

            <li class="list-inline-item">
                <a href="/contact_us/contact_us.html" class="text-light">Contact Us</a>
            </li>

            <li class="list-inline-item">
                <a href="/privacy_policy/privacy_policy.html" class="text-light">Privacy Policy</a>
            </li>
          </ul>
      </div>
      <p class="m-0 text-center text-white">Copyright &copy; Dipesh Pal 2019-2020. All Rights Reserved</p>
    </footer>

     <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    

    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Js min -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.min.js"></script>

    <script>
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text()
                console.log(content)
                var markedContent = marked(content)
                console.log(markedContent)
                $(this).html(markedContent)
             })
             $(".content-markdown img").each(function(){
                $(this).addClass("img-fluid")
             })
        })
    </script>
</body>
</html>

Dipesh_Pal/templates/signup.html
{% extends 'base_layout2.html' %}


{% block title %}<title>Dipesh Pal - SignUp</title>{% endblock %}

{% block signupli %} class="nav-item active" {% endblock %}

{% block content %}
    <div>
      <form class="site-form" method="post">
          <h1 class="h1">Signup</h1>
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="SignUp">
      </form>
  </div>
{% endblock %}