Dipesh_Pal/Dipesh_Pal/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from home.sitemaps import PostSitemap, StaticViewSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'posts': PostSitemap,
    'static': StaticViewSitemap(['sitemap',
                                 'home:list',
                                 'home:News', 'home:android', 'home:PC', 'home:Others', 'home:create',
                                 'about:about',
                                 'disclaimer:disclaimer',
                                 'contact_us:contact_us',
                                 'videos:videos_page',
                                 ]),
}


urlpatterns = [
    url('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('accounts.urls'), name='accounts'),
    url(r'^', include('home.urls'), name='home'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^about/', include('about.urls'), name='about'),
    url(r'^disclaimer/', include('disclaimer.urls'), name='disclaimer'),
    url(r'^privacy_policy/', include('privacy_policy.urls')),
    url(r'^contact_us/', include('contact_us.urls'), name='contact_us'),
    url(r'^videos/', include('videos.urls'), name='videos'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dipesh_Pal/home/urls.py
from django.conf.urls import url

from . import views


app_name = 'home'


urlpatterns = [
    url(r'^$', views.homepage, name="list"),
    url(r'^News/', views.News, name="News"),
    url(r'^Android/', views.android, name="android"),
    url(r'^PC/', views.PC, name="PC"),
    url(r'^Offers/', views.Offers, name="Offers"),
    url(r'^Others/', views.Others, name="Others"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/', views.article_update, name="post_edit"),
    url(r'^(?P<slug>[\w-]+)/delete/', views.article_delete, name="delete_post"),
]

Dipesh_Pal/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from Dipesh_Pal.utils import unique_slug_generator


# Create your models here.
class Home(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, null=True, blank=True)
    body = models.TextField()
    CATEGORY_CHOICES = [
        ('NEWS', 'News'),
        ('ANDROID', 'Android'),
        ('PC', 'PC'),
        ('OFFERS', 'Offers'),
        ('OTHERS', 'Others'),
    ]
    category = models.CharField(
        max_length=20,
        choices=CATEGORY_CHOICES,
        default='OTHERS',
    )

    link = models.URLField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100]+'...'

    def get_absolute_url(self):
        return '/' + self.title


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(slug_generator, sender=Home)

Dipesh_Pal/home/forms.py
from django import forms
from . import models
from pagedown.widgets import PagedownWidget
from django.contrib.auth.forms import UserChangeForm


class CreateArticle(forms.ModelForm):
    body = forms.CharField(widget=PagedownWidget)
    class Meta:
        model = models.Home
        fields = ['title', 'category', 'body', 'thumb']


class EditPostForm(UserChangeForm):
    body = forms.CharField(widget=PagedownWidget)
    class Meta:
        model = models.Home
        fields = ['title', 'category', 'body', 'thumb']


class DeleteNewForm(forms.ModelForm):
    class Meta:
        model = models.Home
        fields = []

Dipesh_Pal/home/views.py
from django.shortcuts import render, redirect
from . models import Home
from django.contrib.auth.decorators import login_required
from . import forms
from django.core.paginator import Paginator
# from .social_stats_counter import start


def homepage(request):
    # a, b, c = start()
    # print(a, b, c)
    a = 9.7  # YouTube
    b = 343  # Instagram
    c = 50  # Twitter
    homeblog_list = Home.objects.all().order_by('-date')

    # Pagination
    # Show 10 Post Per Page
    paginator = Paginator(homeblog_list, 10)

    page = request.GET.get('page')
    homeblog = paginator.get_page(page)
    articles = {
        'articles': homeblog,
        'youtube_subscriber': a,
        'instagram_followers': b,
        'twitter_followers': c,
    }
    return render(request, 'home/home.html', articles)


def android(request):
    homeblog_list = Home.objects.all().order_by('-date')
    paginator = Paginator(homeblog_list, 10)
    page = request.GET.get('page')
    homeblog = paginator.get_page(page)
    return render(request, 'home/Android.html', {'articles': homeblog})


def PC(request):
    homeblog_list = Home.objects.all().order_by('-date')
    paginator = Paginator(homeblog_list, 10)
    page = request.GET.get('page')
    homeblog = paginator.get_page(page)
    return render(request, 'home/PC.html', {'articles': homeblog})


def News(request):
    homeblog_list = Home.objects.all().order_by('-date')
    paginator = Paginator(homeblog_list, 10)
    page = request.GET.get('page')
    homeblog = paginator.get_page(page)
    return render(request, 'home/News.html', {'articles': homeblog})


def Offers(request):
    homeblog_list = Home.objects.all().order_by('-date')
    paginator = Paginator(homeblog_list, 10)
    page = request.GET.get('page')
    homeblog = paginator.get_page(page)
    return render(request, 'home/Offers.html', {'articles': homeblog})


def Others(request):
    homeblog_list = Home.objects.all().order_by('-date')
    paginator = Paginator(homeblog_list, 10)
    page = request.GET.get('page')
    homeblog = paginator.get_page(page)
    return render(request, 'home/Others.html', {'articles': homeblog})


def article_detail(request, slug):
    article = Home.objects.get(slug=slug)
    return render(request, 'home/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.user.is_staff:
        if request.method == 'POST':
            form = forms.CreateArticle(request.POST, request.FILES)
            if form.is_valid():
                # save article to db
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()
                return redirect('home:list')
        else:
            form = forms.CreateArticle()
        return render(request, 'home/article_create.html', {'form': form})
    else:
        return render(request, 'home/not_valid_user.html')


@login_required(login_url="/accounts/login/")
def article_delete(request, slug):
   if request.user.is_staff:
        user = request.user
        try:
            Home.objects.get(slug=slug, author_id=user).delete()
            return render(request, 'home/article_delete.html')
        except:
            return render(request, 'home/not_valid_user.html')
   else:
        return render(request, 'home/not_valid_user.html')


@login_required(login_url="/accounts/login/")
def article_update(request, slug):
    instance = Home.objects.get(slug=slug)
    user = request.user
    try:
        print("### ", Home.objects.get(slug=slug, author_id=user))
        if request.user.is_staff:
            form = forms.EditPostForm(instance=instance)
            args = {'form': form}
            # The line below cause delete previous post when do not save
            return render(request, 'home/article_edit.html', args)
        else:
            return render(request, 'home/not_valid_user.html')
    except:
        return render(request, 'home/not_valid_user.html')

Dipesh_Pal/home/templates/home/Android.html
{% extends 'base_layout.html' %}

{% block homeli %} class="nav-item active" {% endblock %}
{% block Androidli %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Android-</h1>
        <div class="container">
            {% for article in articles %}
                {% if article.category == 'ANDROID' %}
                    <p>Category: {{ article.category }}</p>
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{% url 'home:detail' slug=article.slug %}">{{ article.author }}</a>
                                <small class="text-muted">{{ article.date | date:"F d, Y" }}</small>
                            </div>
                            <h2><a id="teal_heading" class="article-title" href="{% url 'home:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                            <p class="article-content content-markdown">{{ article.snippet }}</p>
                        </div>
                    </article>
                {% endif %}
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">
                            {% if articles.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">previous</a></li>
                            {% endif %}

                            <span class="current">
                                <li class="page-item active"><a class="page-link">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a></li>
                            </span>

                            {% if articles.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">next</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a></li>
                            {% endif %}
                        </span>
                </ul>
            </nav>
        </div>
{% endblock %}

Dipesh_Pal/home/templates/home/News.html
{% extends 'base_layout.html' %}

{% block homeli %} class="nav-item active" {% endblock %}
{% block Newsli %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>News-</h1>
        <div class="container">
            {% for article in articles %}
                {% if article.category == 'NEWS' %}
                   <p>Category: {{ article.category }}</p>
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{% url 'home:detail' slug=article.slug %}">{{ article.author }}</a>
                                <small class="text-muted">{{ article.date | date:"F d, Y" }}</small>
                            </div>
                            <h2><a id="teal_heading" class="article-title" href="{% url 'home:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                            <p class="article-content content-markdown">{{ article.snippet }}</p>
                        </div>
                    </article>
                {% endif %}
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">
                            {% if articles.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">previous</a></li>
                            {% endif %}

                            <span class="current">
                                <li class="page-item active"><a class="page-link">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a></li>
                            </span>

                            {% if articles.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">next</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a></li>
                            {% endif %}
                        </span>
                </ul>
            </nav>
        </div>
{% endblock %}

Dipesh_Pal/home/templates/home/Offers.html
{% extends 'base_layout.html' %}

{% block homeli %} class="nav-item active" {% endblock %}
{% block Offersli %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Others-</h1>
        <div class="container">
            {% for article in articles %}
                {% if article.category == 'OFFERS' %}
                    <p>Category: {{ article.category }}</p>
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{% url 'home:detail' slug=article.slug %}">{{ article.author }}</a>
                                <small class="text-muted">{{ article.date | date:"F d, Y" }}</small>
                            </div>
                            <h2><a id="teal_heading" class="article-title" href="{% url 'home:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                            <p class="article-content content-markdown">{{ article.snippet }}</p>
                        </div>
                    </article>
                {% endif %}
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">
                            {% if articles.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">previous</a></li>
                            {% endif %}

                            <span class="current">
                                <li class="page-item active"><a class="page-link">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a></li>
                            </span>

                            {% if articles.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">next</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a></li>
                            {% endif %}
                        </span>
                </ul>
            </nav>
        </div>
{% endblock %}

Dipesh_Pal/home/templates/home/Others.html
{% extends 'base_layout.html' %}

{% block homeli %} class="nav-item active" {% endblock %}
{% block Othersli %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Others-</h1>
        <div class="container">
            {% for article in articles %}
                {% if article.category == 'OTHERS' %}
                    <p>Category: {{ article.category }}</p>
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{% url 'home:detail' slug=article.slug %}">{{ article.author }}</a>
                                <small class="text-muted">{{ article.date | date:"F d, Y" }}</small>
                            </div>
                            <h2><a id="teal_heading" class="article-title" href="{% url 'home:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                            <p class="article-content content-markdown">{{ article.snippet }}</p>
                        </div>
                    </article>
                {% endif %}
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">
                            {% if articles.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">previous</a></li>
                            {% endif %}

                            <span class="current">
                                <li class="page-item active"><a class="page-link">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a></li>
                            </span>

                            {% if articles.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">next</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a></li>
                            {% endif %}
                        </span>
                </ul>
            </nav>
        </div>
{% endblock %}

Dipesh_Pal/home/templates/home/PC.html
{% extends 'base_layout.html' %}

{% block homeli %} class="nav-item active" {% endblock %}
{% block Pcli %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>PC-</h1>
        <div class="container">
            {% for article in articles %}
                {% if article.category == 'PC' %}
                    <p>Category: {{ article.category }}</p>
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{% url 'home:detail' slug=article.slug %}">{{ article.author }}</a>
                                <small class="text-muted">{{ article.date | date:"F d, Y" }}</small>
                            </div>
                            <h2><a id="teal_heading" class="article-title" href="{% url 'home:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                            <p class="article-content content-markdown">{{ article.snippet }}</p>
                        </div>
                    </article>
                {% endif %}
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">
                            {% if articles.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">previous</a></li>
                            {% endif %}

                            <span class="current">
                                <li class="page-item active"><a class="page-link">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a></li>
                            </span>

                            {% if articles.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">next</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a></li>
                            {% endif %}
                        </span>
                </ul>
            </nav>
        </div>
{% endblock %}

Dipesh_Pal/home/templates/home/article_create.html
{% extends 'base_layout2.html' %}


{% block articleCreateli %} class="nav-item active" {% endblock %}


{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
    <div class="create-article">
        <form class="site-form" action="{% url 'home:create' %}" method="post" enctype="multipart/form-data">
            <h2>Create your article</h2>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

Dipesh_Pal/home/templates/home/article_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Deleted</h1>
<a href="{% url 'home:list' %}">Click Here to go back to home</a>
</body>
</html>

Dipesh_Pal/home/templates/home/article_delete_warning.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Warning</h1>
<a  href="delete_confirm">Delete</a>
</body>
</html>

Dipesh_Pal/home/templates/home/article_detail.html
{% extends 'base_layout_ads.html' %}

{% block content %}
    {% if user.is_authenticated%}
        {% if user.is_staff %}
        <ul>
          <a href="edit" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Update</a>
          <a href="delete" class="btn btn-danger btn-lg active" role="button" aria-pressed="true">Delete</a>
        </ul>
        {% endif %}
    {% endif %}

    <div class="article-detail">
        <h2>{{ article.title }}</h2>
        <img width="100%" height="100%" class="article-image" src="{{ article.thumb.url }}"/>

            <!-- AddToAny BEGIN -->
            <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
            <a class="a2a_button_facebook"></a>
            <a class="a2a_button_twitter"></a>
            <a class="a2a_button_email"></a>
            <a class="a2a_button_linkedin"></a>
            <a class="a2a_button_whatsapp"></a>
            <a class="a2a_button_telegram"></a>
            <a class="a2a_button_pinterest"></a>
            <a class="a2a_button_skype"></a>
            <a class="a2a_button_sms"></a>
            <a class="a2a_button_google_gmail"></a>
            </div>
            <script async src="https://static.addtoany.com/menu/page.js"></script>
            <!-- AddToAny END -->

        <div class="article content-markdown">
            <p>{{ article.body }}</p>
        </div>
            <p>-{{ article.author }}, {{ article.date }}</p>

    </div>
{% endblock %}

Dipesh_Pal/home/templates/home/article_edit.html
{% extends 'base_layout2.html' %}


{% block articleCreateli %} class="nav-item active" {% endblock %}


{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}


{% block script %}
<!-== Enable this if you need warning ==->
<!--    <script type="text/javascript">-->
<!--        function codeAddress() {-->
<!--            alert('Do Not Close or Press back without pressing "Update" Button');-->
<!--        }-->
<!--        window.onload = codeAddress();-->
<!--    </script>-->

{% endblock %}

{% block content %}
<h1>Article Edit</h1>
    <h3 style="color:red">Do Not Close or Press back without pressing "Update" Button</h3>
    <div class="create-article">
        <form class="site-form" action="{% url 'home:create' %}" method="post" enctype="multipart/form-data">
            <h2>Create your article</h2>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Update">
        </form>
    </div>

{% endblock %}

Dipesh_Pal/home/templates/home/home.html
{% extends 'base_layout.html' %}

{% block homeli %} class="nav-item active" {% endblock %}
{% block Allli %} class="nav-item active" {% endblock %}

{% block content %}
    <!--<h1>All Topics-</h1>-->
        <div class="container">
            {% for article in articles %}
                {{ article.a }}
                   <p>Category: {{ article.category }}</p>
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{% url 'home:detail' slug=article.slug %}">{{ article.author }}</a>
                                <small class="text-muted">{{ article.date | date:"F d, Y" }}</small>
                            </div>
                            <h2><a id="teal_heading" class="article-title" href="{% url 'home:detail' slug=article.slug %}">{{ article.title }}</a></h2>

                            <div class="row">
                                <div class="col-sm-3">
                                    <img class="article-image" src="{{ article.thumb.url }}"/>
                                </div>
                                <div class="col-sm-8">
                                      <p class="article-content content-markdown">{{ article.snippet }}</p>
                                </div>
                            </div>
                        </div>
                    </article>
            {% endfor %}

            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">
                            {% if articles.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">previous</a></li>
                            {% endif %}

                            <span class="current">
                                <li class="page-item active"><a class="page-link">Page {{ articles.number }} of {{ articles.paginator.num_pages }}  </a></li>
                            </span>

                            {% if articles.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">next</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a></li>
                            {% endif %}
                        </span>
                </ul>
            </nav>
        </div>
{% endblock %}

Dipesh_Pal/home/templates/home/not_valid_user.html
{% extends 'base_layout2.html' %}


{% block articleCreateli %} class="nav-item active" {% endblock %}

{% block content %}
    <div class="create-article">
        <h1>You are not a valid user, contact administrator or go back to home</h1>
    </div>
{% endblock %}